### ISSUE TITLE
Auto-register aliases declared in sd scripts?

### ISSUE THREAD

**Issue by cweagans** [ianthehenry/sd#20]
I'm not 100% sure how this would work, but rather than writing a script (for instance, `sd git update-repo`) and separately defining an alias in my zsh config (`alias gup='sd git update-repo'`), it'd be cool if I could add some entry to the header of an `sd` script that would cause the zsh plugin to register an alias on my behalf. That way, everything about the script is sort of self contained.

It's not a huge hassle to define the aliases separately, but I definitely have a number of aliases as shortcuts to `sd` scripts, so maybe it'd be a useful feature?

Something along these lines:

```bash
#!/usr/bin/env bash

# Update a repo from the right upstream.
#
# This command will figure out the right branch and upstream to update from and
# also update the fork main/master branch as well if necessary.
#
# Alias: gup
#
# [...]
```

**Comment by ianthehenry** [comment]
Hmm, you could definitely put something in your zshrc to automatically set up aliases like this, but I don't think it makes sense to add as a general feature of sd. For example, using `rg`:

```bash
eval $(cd ~/sd; rg '^# Alias:' --with-filename --no-heading --no-line-number | sed -E -e 's|/| |g' -e 's/([^:]+):# Alias: (.+)/alias \2="sd \1"/')
```

Of course you need to re-run that any time you add a new alias, and it won't remove any aliases that you change or delete, but might work well enough for your workflow.

**Comment by cweagans** [comment]
Thanks! That worked really well!

https://github.com/cweagans/dotfiles/commit/6ee34a860b16a353b90453c7eb1ae144cafab057
