### ISSUE TITLE
README doesn't explain how to install tab completion

### ISSUE THREAD

**Issue by davidmankin** [ianthehenry/sd#6]
Hi. Still a noob user here :)  
I have put sd on my path like the readme says.  I've never used zsh before this new mac so I don't know what it takes to get the advertised awesome tab completion installed though.  The readme implies there's nothing to do and it's magic, but it doesn't seem to work for me.  

Thanks,
David

sd version: 1.0.1

**Comment by ianthehenry** [comment]
Hi David! The instructions for adding tab completion were pretty hidden at the end of the installation instructions. I've made them more prominent in the latest README, which hopefully clarifies things a bit. Could you take a look at the latest installation instructions and let me know if that makes sense?

**Comment by davidmankin** [comment]
Ah! I had thought fpath was only if you were installing as a shell function, so I skipped it.  This is much clearer. Thanks.
