### ISSUE TITLE
Interest in Fish Completions?

### ISSUE THREAD

**Issue by arcuru** [ianthehenry/sd#7]
I came across this as a blog post months ago and wrote a _very_ hacky fish completion script. Would you have any interest in it?

Since I wrote it just for myself it needs a few updates to align with the zsh completions script. I think you added some new arguments (`--help`, `--cat`, etc) so it's a little out of date, and I also hardcoded it to use `~/.local/sd`. I've been using it for months without any issues, so it is pretty stable.

Here is the file as a gist: https://gist.github.com/patricksjackson/5065e4a9d8e825dafc7824112f17a5e6

**Comment by ianthehenry** [comment]
Hey thanks! I don't want to officially support fish at this point, but I added a link to this gist in the README for others.
