### ISSUE TITLE
Name clash with https://github.com/chmln/sd

### ISSUE THREAD

**Issue by vgivanovic** [ianthehenry/sd#9]
On Arch Linux at least, this `sd` has a name clash with the `sd` from `https://github.com/chmln/sd`.

If it were up to me, I'd rename/refactor this `sd` because `https://github.com/chmln/sd` existed before this `sd`.

**Comment by ianthehenry** [comment]
Oh, yeah, I know. This `sd` pre-dates that `sd` [by about nine months](https://github.com/ianthehenry/dotfiles/commit/7c4a8f07a39a3bb8716880ddce64066405a5de16), although that is a small consolation if you're trying to use both projects side-by-side.

I'm not going to rename it as my fingers have gotten very used to typing `sd` over the last 4.5 years, but let me know if you're trying to package this for Arch and this is causing problems.
